# -*- coding: utf-8 -*-
"""logistic regression

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mM2NFCvnN4dQ9XfJXpLBeXSX3eEtyQKv
"""

from google.colab import files
uploaded = files.upload()
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

def trimmer(s):
    top = s.strip('\n');
    result = ''.join([i for i in top if not i.isdigit()])
    fin = result.replace(".", "", 1).strip('\t')
    fin = fin.lower()
    fin = re.sub(r'[^\w\s]','',fin)
    fin = fin.strip(' ')
    return fin

import re

def listed(filename):
  trimmed = []
  with open (filename) as loaded:
    listed = loaded.readlines()
    for line in listed:
      if line != "":
        stripped = trimmer(line)
        trimmed.append(stripped)
      else:
        continue
    return trimmed

#print(listed('Questions.txt'))

questions = listed('Questions.txt')
questions = questions[:-5]
topics = listed('Topics.txt')

def topic_log(test_file):
  logisticRegr = LogisticRegression()

  tfidf = TfidfVectorizer(sublinear_tf=True, min_df=5, norm='l2', encoding='latin-1', ngram_range=(1, 2), stop_words='english')
  features = tfidf.fit_transform(questions).toarray()

  X_train, X_test, y_train, y_test = train_test_split(questions, topics, random_state = 0)
  count_vect = CountVectorizer()
  X_train_counts = count_vect.fit_transform(X_train)
  tfidf_transformer = TfidfTransformer()
  X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
  model = logisticRegr.fit(X_train_tfidf, y_train)
      
  test = listed(test_file)
  results = open("topic_results.txt","w+")
  for line in test:
    quest = count_vect.transform([line])
    ans = model.predict(quest)[0]
#     print(ans)
#     print('\n')
    results.write(ans)
    results.write('\n')
  results.close()

topic_log('Questions.txt')

